name = "VBDiscretePOMDP"
uuid = "0c60eff4-4fac-4feb-8363-bdc8ccab6c50"
version = "0.0.1"
authors = ["Jonathan Ehrenreich Laursen", "Samuel William Nehrer", "Peter Thestrup Waade"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
ActiveInference = "688b0e7a-0122-4325-8669-5ff08899a59e"

[extensions]
ActiveInferenceExt = "ActiveInference"

[compat]
julia = "1.12"
LinearAlgebra = "1.0"
ActiveInference = "0.1"